# permissions for end users to edit esclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: es564-operator
    app.kubernetes.io/managed-by: kustomize
  name: escluster-editor-role
rules:
- apiGroups:
  - elasticsearch.yasy.run
  resources:
  - esclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elasticsearch.yasy.run
  resources:
  - esclusters/status
  verbs:
  - get
